### ISSUE TITLE
[Bug]: Transfer Funds confirmation has >100% spending and <0% savings

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1942] opened 2024-06-04 11:21 UTC
### Describe the bug

When attempting to transfer funds from savings to spending, on the confirmation page I see spending at 144% and savings at -44%. This might have something to do with my pending LN connection. See screenshots and ldk log for details.

[bitkit_ldk_logs_1717499417210.zip](https://github.com/user-attachments/files/15550526/bitkit_ldk_logs_1717499417210.zip)

### Reproduce

1. With an active LN connection ~(AND with pending LN connection?)~
2. Open Transfer Funds page
3. Increase spending balance
4. Proceed to PLEASE CONFIRM page
5. Observe unrealistic percentage values

### Screenshots / Recording

<img src="https://github.com/synonymdev/bitkit/assets/74595920/3c5835ad-8210-4f1c-b362-33050c82c51f" width="300">

<img src="https://github.com/synonymdev/bitkit/assets/74595920/76fb5f98-f1e8-4c38-aa5c-f938d6773a5c" width="300">

<img src="https://github.com/synonymdev/bitkit/assets/74595920/2c8a8215-e4ee-4848-8a19-4fcbafdbfc9d" width="300">

<img src="https://github.com/synonymdev/bitkit/assets/74595920/607e7b9a-2d6a-4e18-b45f-8ed31a45fc1f" width="300">

https://github.com/synonymdev/bitkit/assets/74595920/762d894e-c7b1-4b7d-8a68-1ecab2fb36f2

### Operating system

Android 13 TKQ1.221114.001

### Bitkit version

1e714a948f69789cec42936226bfeb43ac8cf5e6

**Comment by JeanlChristophe** [comment] 2024-06-21 13:08
Couldn't reproduce the issue for the moment. Either at the conference.

**Comment by catch-21** [comment] 2024-06-21 13:29
At the very least, we should handle such a scenario, regardless of the cause.  For example, the UI restarts/crashes Bitkit when impossible values occur.

**Comment by JeanlChristophe** [comment] 2024-09-03 08:59
With new design, we can't have this issue anymore. Closing it.

**Closed as completed by JeanlChristophe** 2024-09-03 08:59 UTC
Labels: bug, triage
