### ISSUE TITLE
Advanced Manual Setup flow for LN channel isn't available for US/Canadia

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2269] opened 2024-10-01 10:40 UTC

**Comment by dzdidi** [comment] 2024-10-01 10:49
I assume this is related to creating connection with non-blocktank nodes, right? If so it needs to be adjusted on bitkit end.

**Comment by pwltr** [comment] 2024-10-01 10:54
Duplicate of https://github.com/synonymdev/bitkit/issues/2252

**Closed as completed by pwltr** 2024-10-01 10:54 UTC

**Comment by catch-21** [comment] 2024-11-04 16:50
already tested in #2252
