### ISSUE TITLE
[Bug]: Receive multiple payment notifications.

### ISSUE THREAD

**Issue by MiguelMedeiros** [synonymdev/bitkit-react-native#1155] opened 2023-07-11 14:15 UTC
### Describe the bug

After receiving the first payment notification I got another one.

### Reproduce

1. Receive a payment
2. It will show the animation with the amount, etc.
3. Wait a little bit
4. It will show the animation with the amount, etc.

### Operating system

Android 12

### Bitkit version

58

**Comment by pwltr** [comment] 2023-08-10 12:00
I've never had this issue, @MiguelMedeiros anything special in your setup? Did you set a different electrum server? Does this happen for every transaction? Onchain or Lightning?

**Comment by MiguelMedeiros** [comment] 2023-08-10 12:27
Nothing special on my setup. 
Only happend onchain.

**Comment by pwltr** [comment] 2024-03-19 11:38
I think this issue was caused by backgrounding the app on Android for a few minutes, may have been fixed by #1610, closing.

**Closed as completed by pwltr** 2024-03-19 11:38 UTC
Labels: bug
