### ISSUE TITLE
[Bug]: Transfer to savings shows Initiating suggestion card indefinitely

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2260] opened 2024-09-30 07:15 UTC
### Describe the bug

After transferring from spending to savings the Initiating 'Keep app open' suggestion card remains visible once all transactions are seen and even once confirmed. I think it should disappear once we see all expected transactions in mempool.

TODO: **check whether this is only the case for closing a manually added connection**

### Operating system

Android 14

### Bitkit version

1.0.5 (136)

**Comment by pwltr** [comment] 2024-09-30 10:19
Duplicate of https://github.com/synonymdev/bitkit/issues/2190

**Closed as completed by pwltr** 2024-09-30 10:19 UTC
Labels: bug, triage
