### ISSUE TITLE
[Bug]: Slider does not work when paying.

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2220] opened 2024-09-11 07:33 UTC
### Describe the bug

After scanning an LN invoice, the slider doesn't work and remains frozen but then if you “re-try” then the slider works

### Operating system

iOS

### Bitkit version

v133

**Comment by catch-21** [comment] 2024-09-11 08:12
Duplicate of https://github.com/synonymdev/bitkit/issues/1334

**Closed as completed** 2024-09-11 08:17 UTC
Labels: bug, triage
