### ISSUE TITLE
[Bug]: Duplicated activities

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1228] opened 2023-09-07 19:57 UTC
### Describe the bug

I restored a wallet that had an open Lightning channel and I couldn't restore due to the same issue at #1130. Now, many of my activities are duplicated.

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/93796166/9b96d9e6-fd7b-4b11-9548-03626ba55473

### Operating system

iOS 17

### Bitkit version

64

**Comment by pwltr** [comment] 2023-09-27 15:03
@limpbrains Do you think this issue is also fixed by https://github.com/synonymdev/bitkit/pull/1271?

**Comment by limpbrains** [comment] 2023-09-27 15:38
Yes

**Comment by mattcrv** [comment] 2024-01-12 00:03
@limpbrains, it looks like there was a regression here, this just happened following a CJIT open:

https://github.com/synonymdev/bitkit/assets/93796166/87e5c13d-cb4c-4ec1-8a71-cababbcd7b5d

**Comment by JeanlChristophe** [comment] 2024-01-12 11:01
Pav, Ivan and I can't reproduce this issue on v94

**Comment by mattcrv** [comment] 2024-01-12 13:30
Things have gone crazy over here:

https://github.com/synonymdev/bitkit/assets/93796166/c61148d3-b86f-47af-9ecb-b7c4a5b23cb9

**Comment by JeanlChristophe** [comment] 2024-01-29 14:11
@mattcrv can you test it again with v98? Jay should I fixed it but I prefer to test it to be sure as you had this issue.

**Comment by mattcrv** [comment] 2024-01-29 14:46
> @mattcrv can you test it again with v98? Jay should I fixed it but I prefer to test it to be sure as you had this issue.

Just tested on 99. Not sure if expected, but those payments received three weeks ago via CJIT are still duplicated on my activities list. I didn't have more duplicated activities since then.

https://github.com/synonymdev/bitkit/assets/93796166/1280bea9-a605-4da1-9cf8-c96d3b3e2b91

**Comment by JeanlChristophe** [comment] 2024-01-29 14:50
@pwltr can you have a look about this issue?

**Comment by pwltr** [comment] 2024-01-30 12:17
It sounds like the issue is fixed on the latest release? If so the task is to find a way to clean up old duplicated transactions which I'm not sure is worth the effort seeing this issue has only been reported once. I'd suggest we revisit this if it happens again.

**Comment by JeanlChristophe** [comment] 2024-01-30 14:27
From a new wallet, using testnet I received funds with a bech32 address. However, when I change to Native Segwit or Legacy and try to send sats, there is $0.00 available.

**Comment by JeanlChristophe** [comment] 2024-01-30 14:28
Tested few times already but couldn't reproduce it.

**Comment by pwltr** [comment] 2024-04-24 11:08
Looks like this doesn't happen anymore. Closing for now.

**Closed as completed by pwltr** 2024-04-24 11:08 UTC
Labels: bug, triage
