### ISSUE TITLE
[Bug]: (Regtest) Restore doesn't retain association between transaction and contact

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1640] opened 2024-04-12 09:46 UTC
### Describe the bug

When a payment is made to a contact the transaction listed in Activity has the contact picture and is associated with that contact. After a wallet restore both the transaction list and the contact list are retained but the association of each transaction with the contact profile is not.

### Screenshots / Recording

Before restore the send transaction has association with contact:
![before](https://github.com/synonymdev/bitkit/assets/74595920/bf1e317a-1c04-45d8-9af6-cf1a85b39718)
After restore the send transaction has no association to the contact:
![after](https://github.com/synonymdev/bitkit/assets/74595920/8811779f-14d4-4255-9c8b-76b51b740e5b)

### Operating system

Android 13 TKQ1.220829.002

### Bitkit version

v1.0.0-beta.113

**Comment by catch-21** [comment] 2024-04-12 13:01
I tried this again on mainnet and did not experience this issue. Performed a SlashPay transaction and after wallet restore the transaction still has association with the contact.

**Comment by JeanlChristophe** [comment] 2024-05-23 07:39
I can't reproduce this issue too. Closing it.

**Closed as completed by JeanlChristophe** 2024-05-23 07:39 UTC
Labels: bug, triage
