### ISSUE TITLE
[Bug]: Low sat/bytes transactions

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#975] opened 2023-04-17 08:58 UTC
### Describe the bug

When a user wants to make a transaction with very low fees, such as 1sat/bytes, an error message appears and the transaction does not work. 

"Unable to broadcast transaction: please check your conne action and try again. The transaction was rejected by the network rules".

However, it works on other wallets. 

### Operating system

Graphene OS, iOS

### Bitkit version

v39

**Comment by pwltr** [comment] 2023-04-17 09:13
Could not reproduce this issue yet. I sent several onchain txs with a fee rate of 1sat/vbyte on mainnet. @JeanlChristophe Do you have more details about the transaction that failed for you? Number of inputs/outputs, amount, address type etc. ? I can work on this issue.

**Comment by pwltr** [comment] 2023-05-25 12:27
I retested this using all address type combinations (Bitkit to Bitkit) and cross-checking fees with https://jlopp.github.io/bitcoin-transaction-size-calculator. All transactions went through successfully.

Closing this for now. Please reopen if this keeps happening.

**Closed as completed by pwltr** 2023-05-25 12:27 UTC
Labels: bug
