### ISSUE TITLE
[Bug]: LNURL-Pay: Lightning invoice expired

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1201] opened 2023-08-14 14:00 UTC
### Describe the bug

I tried funding my Stacker News account with two different invoice amounts, and it kept returning "lightning invoice expired". The same issue is happening when funding my LNMarkets account and donating to [BTC Map](https://btcmap.org/support-us) through LNURLp. 

I could pay all three with Phoenix on my first attempt, so I think the issue wasn't the invoices. It's worth noting that I can withdraw from my Stacker News balance through LNURLw normally.

### Screenshots / Recording

![IMG_A7CEDB0656A6-1](https://github.com/synonymdev/bitkit/assets/93796166/0838e784-06c9-4eea-990a-74a6d04ed874)

### Operating system

iOS 17

### Bitkit version

61

**Comment by limpbrains** [comment] 2023-09-18 13:29
For me both destinations failed with `invoice_payment_fail_sending` error, I can't say why, maybe @Jasonvdb can?

**Comment by JeanlChristophe** [comment] 2024-05-23 08:51
I can't reproduce this issue. Closing it.

**Closed as completed by JeanlChristophe** 2024-05-23 08:51 UTC
Labels: bug, triage
