### ISSUE TITLE
[Bug]: No activity yet

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1355] opened 2023-10-24 12:45 UTC
### Describe the bug

The user's wallet displayed no activity. The first consolation prize activity was the first transaction to be displayed properly.

### Reproduce

No idea how to reproduce it, unfortunately.

### Screenshots / Recording

![IMG_2428](https://github.com/synonymdev/bitkit/assets/93796166/b12e170c-4cde-4139-baaa-0fb2a5243cd0)
![IMG_2429](https://github.com/synonymdev/bitkit/assets/93796166/a7b5ae87-6713-40f0-8640-e71f922f4026)
![IMG_2430](https://github.com/synonymdev/bitkit/assets/93796166/8719063c-c670-45b2-8f7e-e7708d567655)

### Operating system

Android

**Comment by pwltr** [comment] 2023-12-15 17:46
Not able to reproduce this one.

**Comment by JeanlChristophe** [comment] 2023-12-28 14:54
@pwltr not able too

**Comment by JeanlChristophe** [comment] 2024-01-29 14:06
Fixed on v98

**Closed as completed by JeanlChristophe** 2024-01-29 14:06 UTC
Labels: bug, triage
