### ISSUE TITLE
[Bug]: 0 spending balance

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1208] opened 2023-08-15 14:15 UTC
### Describe the bug

some UX issues not sure if its a bug but when I open a channel, I receive notification that Instant Payments are available - its says open connection but on the home screen it says pending balance. The app was ON during the entire time. Positive side is it took less than 5 min for Bitkit to open a channel. But then under spending balance I can see 0 - mixed messages (see screenshots).

I backed up wallet and try to wipe and restore. Initially app crashed without providing option to send a report. I then restored the wallet only to find out there was no channel opened (see screenshot), amount was taken and now missing after restore (wallet has not indicated it was even LN tx).

### Screenshots / Recording

![photo_2023-08-15_15-53-29](https://github.com/synonymdev/bitkit/assets/119061223/3c519641-adc7-476c-9c76-2e245bc2ed09)
![photo_2023-08-15_15-53-28](https://github.com/synonymdev/bitkit/assets/119061223/7c654ca1-08a6-4963-83a8-f0b1f13edf0d)
![photo_2023-08-15_15-53-27](https://github.com/synonymdev/bitkit/assets/119061223/30007494-3753-4d82-b289-85f652b71196)
![photo_2023-08-15_16-30-53](https://github.com/synonymdev/bitkit/assets/119061223/b3668a53-44f4-43d0-b14d-46a036f1f22b)
[bitkit_ldk_logs_1692108700214.zip](https://github.com/synonymdev/bitkit/files/12344955/bitkit_ldk_logs_1692108700214.zip)
![photo_2023-08-15_16-30-52](https://github.com/synonymdev/bitkit/assets/119061223/2665251f-90fe-4213-b54c-618e821d540e)
![photo_2023-08-15_16-23-32](https://github.com/synonymdev/bitkit/assets/119061223/eddd5880-da83-4bec-8e64-0b182a531289)

### Operating system

iPhone 6S 

### Bitkit version

v63

**Comment by JeanlChristophe** [comment] 2023-08-15 14:30
I encountered the same issue. Even though the transaction status had been confirmed of 11 times, my spending balance was 0 sats. After the 11th confirmation, the balance updated, and I am now able to perform Lightning transactions without any issues.

**Comment by Jasonvdb** [comment] 2023-08-15 14:43
I think the zero spending balance issue might be just the app state not auto updating and being in sync with LDK. The restore bug is separate.

**Comment by pwltr** [comment] 2023-09-29 10:33
> some UX issues not sure if its a bug but when I open a channel, I receive notification that Instant Payments are available - its says open connection but on the home screen it says pending balance. The app was ON during the entire time. Positive side is it took less than 5 min for Bitkit to open a channel. But then under spending balance I can see 0 - mixed messages (see screenshots).

The first part is a known issue and tracked here: https://github.com/synonymdev/bitkit/issues/1261

Since the channel wasn't actually open yet (it is under pending in the screenshot) we can't add the local channel balance to the overall spending balance since you cannot use it yet. So working as expected here.

Assigning to @Jasonvdb for the second part

**Comment by pwltr** [comment] 2024-09-10 10:41
Closing this, seems outdated.

**Closed as completed by pwltr** 2024-09-10 10:41 UTC
Labels: bug
