### ISSUE TITLE
Unable to pay contact via SlashPay, despite both of us having CJIT

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1742] opened 2024-04-26 10:10 UTC
### Describe the bug

Both me and James have CJIT working. 
He is able to pay-to-contact using LN / CJIT (albeit only after deleting me and re-adding me).
I tried to do the same and it defaults to on-chain.
I tried deleting him as a contact and re-adding him, same result.
When I specify an a small amount (5-10 sats), and I click on the next screen, it shows I am sending 0 sats (see video) 

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/119061223/ecdbe124-c7d9-4a40-b113-c8f48a775332

[bitkit_ldk_logs_1714126209308.zip](https://github.com/synonymdev/bitkit/files/15129166/bitkit_ldk_logs_1714126209308.zip)

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v115

**Comment by catch-21** [comment] 2024-04-26 14:45
We retried this with a new wallet/profile and shortly after this new wallet setup a LN channel via CJIT the profile also updated correctly with the option for instant payment. We are unable to reproduce this now so closing.

**Closed as completed by catch-21** 2024-04-26 14:45 UTC
Labels: bug, triage
