### ISSUE TITLE
[Bug]: Discrepancy between Suggestion card saying channel paid and channel not being setup and ready to receive

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1386] opened 2023-11-17 10:54 UTC
### Describe the bug

opened an order with 0 spending balance. After a while the suggestion card indicated that there was payment. I can see the tx history confirms that whith the status being "Confirmed"

However, when I navigate to Settings > Advanced > Lightning Connection - the channel is neither ready nor usable

so I am unable to receive on LN  

### Screenshots / Recording

![photo_2023-11-17_12-51-11](https://github.com/synonymdev/bitkit/assets/119061223/0dbe2612-950b-46a9-a5a7-50d36370eefa)
![photo_2023-11-17_12-51-10](https://github.com/synonymdev/bitkit/assets/119061223/92289fd1-ef2f-4daf-b10c-ce08c6ca770f)
![photo_2023-11-17_12-51-08](https://github.com/synonymdev/bitkit/assets/119061223/2d5a4508-6f25-422c-b312-b7f80089e561)

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v87

**Comment by JeanlChristophe** [comment] 2024-03-26 12:05
Duplicate https://github.com/synonymdev/bitkit/issues/1261 ?

**Comment by pwltr** [comment] 2024-04-24 11:08
Closed for duplicate of https://github.com/synonymdev/bitkit/issues/1261

**Closed as completed by pwltr** 2024-04-24 11:08 UTC
Labels: bug, triage
