### ISSUE TITLE
[Bug]: App crashes after leaving in background and returning to it

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#1454] opened 2024-01-04 14:13 UTC
### Describe the bug

You can reproduce it (on iPhone i checked ) every time just leave this page Lightning Connections for 2 minutes in background and open app

### Reproduce

1. Go to 'Lightning connections' page
2. Wait 2min
3. See error

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/46056211/10c525b7-2bf7-458a-8712-4113441a8254

### Operating system

iOS

**Comment by JeanlChristophe** [comment] 2024-01-04 14:13
[bitkit_ldk_logs_1704377153041.zip](https://github.com/synonymdev/bitkit/files/13830682/bitkit_ldk_logs_1704377153041.zip)

**Comment by pwltr** [comment] 2024-01-04 20:11
I was able to reproduce this on the latest Testflight, LDK logs don't have anything AFAICT, I sent a crash report though @Jasonvdb 

[bitkit_ldk_logs_1704398815669.zip](https://github.com/synonymdev/bitkit/files/13835371/bitkit_ldk_logs_1704398815669.zip)

**Comment by JeanlChristophe** [comment] 2024-02-09 14:39
@Jasonvdb did you have time to have a look?

**Comment by ovitrif** [comment] 2024-02-21 19:12
Tried to repro but without success, I could only test on Android since I don't have an iPhone.
I'll try more.

From LDK logs this is what I noticed, not sure if relevant but adding it here:
- Both logs had `SendChannelReestablish`
- Both had at least one `addPeer` error
- Both had one `listChannels` error

**Comment by ovitrif** [comment] 2024-06-07 19:54
Moved back 2 backlog since it's stale for a couple months.
Issue is currently not reproducible by devs, we should reevaluate after some more weeks if we might close it as it might no longer be reproducible at all.

**Comment by Jasonvdb** [comment] 2024-06-13 06:06
I'm hoping this is a fix so lets move it to testing after next release https://github.com/synonymdev/react-native-ldk/pull/249

**Comment by catch-21** [comment] 2024-07-04 09:39
This is a common scenario so if no iphone user is seeing this now, happy to close it off.

**Closed as completed by catch-21** 2024-07-04 09:39 UTC
Labels: bug, triage
