### ISSUE TITLE
[Bug]: Sent instead of transferred, wrong order fee, camera permission, and crashes

### ISSUE THREAD

**Issue by mattcrv** [synonymdev/bitkit-react-native#1185] opened 2023-08-04 16:04 UTC
### Describe the bug

Four bugs:

1. I CPFP'd a [funding transaction](https://mempool.space/tx/bbcd6a7c751538bebc062491f60c8d378e6799f042f4c7fa68517390790b30e9), and now it says "sent" instead of "transferred/spending balance" in the activity list.
2. The order fee displayed on the connection details screen has still been 1,092 sats for all connections I opened [after Blocktank started having dynamic fees](https://github.com/synonymdev/blocktank-server/pull/13).
3. The app is not asking for permission to access the camera. I had to go to settings to enable it. Also, the spacing above "← Permission" looks off.
4. The app crashes when I switch address types and tap "Receive".

### Reproduce

5. Scroll down to '....'
6. See error

### Screenshots / Recording

![IMG_46A5B2735926-1](https://github.com/synonymdev/bitkit/assets/93796166/905be940-4740-4247-ba27-60ae9bf366f3)
![IMG_71B7C285F9BD-1](https://github.com/synonymdev/bitkit/assets/93796166/215b41dc-a0cd-4514-83ac-487f52cf0dea)
![IMG_8A7351879EE4-1](https://github.com/synonymdev/bitkit/assets/93796166/393ea095-4ddd-4f76-b889-620d2b74c10d)
![IMG_353181F9C366-1](https://github.com/synonymdev/bitkit/assets/93796166/663ef92c-2155-408e-8db5-1f000614bdb6)

### Operating system

iOS 17

### Bitkit version

61

**Comment by JeanlChristophe** [comment] 2023-08-10 09:06
Hi @mattrdec ,

We tried to reproduced the permission to access the camera on iOS and Android but we can't reproduce the issue. Maybe the configuration is coming from your phone?

In the future, can you create a ticket for each bug? That way we can deal with them one by one.

**Comment by pwltr** [comment] 2023-08-10 11:52
The permission screen should only pop up if the user first declined to give the app access to the camera. Fixed the UI [here](https://github.com/synonymdev/bitkit/pull/1196).

**Comment by pwltr** [comment] 2023-09-28 14:38
Closing this because sub issues either have been fixed or tracked elsewhere:

1. Duplicate of https://github.com/synonymdev/bitkit/issues/1229
2. Not sure about the status of dynamic BT fees but there should not be a todo on Bitkit side for this
3. See comment above
4. (Fixed) Duplicate of https://github.com/synonymdev/bitkit/issues/1235

**Closed as completed by pwltr** 2023-09-28 14:38 UTC
Labels: bug, triage
