### ISSUE TITLE
[Bug]: Issue when sending funds to contacts

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1306] opened 2023-10-11 13:14 UTC
### Describe the bug

I added slash ID for Ivan and Flavio via Send Flow
Send > Enter Manually > paste Slash ID 
I was able to successfully send funds to both Ivan and Flavio.

I am using an old wallet (and installed the latest version v75) so I had Ivan's old account.

When I tried to send funds again via Send flow > I can see two icons - green and red one, even though I didn't have either one of them as contacts 

Once I click on the contact and select the amount of sats > I can see the name of 1 of the contacts (Flavio) despite not having him as a contact.

When I repeat the same process for the other contact I don't see a picture or name so I am not sure who I am sending funds to (Ivan said he had put a name, but I couldn't see it) - refer to video and image

### Screenshots / Recording

https://github.com/synonymdev/bitkit/assets/119061223/c1007668-0d31-464b-ab42-f234d388d76f

![bitkit issue](https://github.com/synonymdev/bitkit/assets/119061223/307fbb55-e657-4401-9517-b0f7a312c88d)

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v75

**Comment by Nuhvi** [comment] 2023-11-02 09:16
Talking to Pav, apparently, the issue here is that while migrating to the new version using the web relay, Ivan's profile wasn't resolving.

This could be caused by any of the following scenarios:
1. ~The web relay is not working~ the data is [available](https://webrelay.slashtags.to/8btc8yge8ot1n755ukohijuxyj8cpcgijbqw3g5xrfywdyh7m1dy/profile.json)
2. Ivan's wallet didn't upload the profile to the web relay in time as he himself was migrating from the old Bitkit system.

Still, this problem shouldn't happen because:
1. Bitkit should have had cached the profile regardless of the transport used to download the current version, right? @limpbrains 
2. We are still using the DHT version at least for loading stuff from LNMarkets and similar servers that didn't migrate to the web relay, right?

I am not sure about how Bitkit handled migration, but these are my first thoughts on the matter.

**Comment by JeanlChristophe** [comment] 2023-11-06 09:18
Ivan's profile is resolvable from the web relay just fine (confirmed this with Pav last week). Closing the ticket.

**Closed as completed by JeanlChristophe** 2023-11-06 09:18 UTC
Labels: bug
