### ISSUE TITLE
[Bug]: Possible to have missing 'Received' activity for CJIT channel open

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#2236] opened 2024-09-16 19:56 UTC
### Describe the bug

It is possible to produce a CJIT invoice, but if Bitkit isn't in the foreground when the invoice is paid then it is possible for it to not detect the 'Received' event. This leads to correct spending balance but no activity to assure the user the payment was received.

### Reproduce

1. Start with a Bitkit wallet with no LN channels
2. Tap Receive and produce CJIT invoice
3. Screenshot the invoice
4. Minimise Bitkit
5. Scan to pay the invoice from a different wallet. The LN payment will succeed provided Bitkit is still running in the background. If Bitkit has been killed then LN payment fails and the invoice goes from Pending to Holding to Cancelled state.
6. Now you can kill Bitkit (or leave it for the OS to dispose of after some time)
7. Start Bitkit again
8. Observe new spending balance, but no confetti and no 'Received' activity item. Also observe open Lightning connection in Advanced settings.

### Operating system

Android 14

### Bitkit version

1.0.4 (135)

**Comment by pwltr** [comment] 2024-09-17 08:57
Duplicate of https://github.com/synonymdev/bitkit/issues/1780

**Closed as completed by pwltr** 2024-09-17 08:57 UTC
Labels: bug, triage
