### ISSUE TITLE
[Bug]: When I want to close a channel and I select one, Bitkit deselects all the channels.

### ISSUE THREAD

**Issue by JeanlChristophe** [synonymdev/bitkit-react-native#2175] opened 2024-08-30 09:46 UTC
### Describe the bug

When I want to close a channel and I select one, Bitkit deselects all the channels. It doesn't reproduce all the time.

### Screenshots / Recording

https://github.com/user-attachments/assets/a244ac4e-dc92-43c0-b351-ca85824c8641

### Operating system

GrapheneOS

### Bitkit version

v133

**Comment by pwltr** [comment] 2024-08-30 11:19
I can't reproduce this one.

**Comment by JeanlChristophe** [comment] 2024-08-30 12:55
On tesnet or production?

**Comment by pwltr** [comment] 2024-08-30 15:57
> On tesnet or production?

Regtest, although network shouldn't really matter in this case.

**Comment by JeanlChristophe** [comment] 2024-09-06 10:42
I can't reproduce it also now.

**Comment by pwltr** [comment] 2024-10-10 13:38
Fixed in https://github.com/synonymdev/bitkit/pull/2305

**Closed as completed by pwltr** 2024-10-10 13:38 UTC
Labels: bug, wontfix, triage
