### ISSUE TITLE
[Bug]: Sent to contact is not working

### ISSUE THREAD

**Issue by vforvilela** [synonymdev/bitkit-react-native#804] opened 2023-01-03 00:19 UTC
### Describe the bug

When I try to pay a contact, nothing happens

### Reproduce

1. Click on 'send'
2. Click on 🙍‍♂️
3. Click on any contact

### Operating system

iOS 16.1.2

### Bitkit version

v1.0 (23)

**Comment by pwltr** [comment] 2023-01-03 11:10
Duplicate of https://github.com/synonymdev/bitkit/issues/744

**Closed as completed by pwltr** 2023-01-03 11:10 UTC
Labels: bug
