### ISSUE TITLE
Lack of available savings could be made clearer when sending onchain payment

### ISSUE THREAD

**Issue by catch-21** [synonymdev/bitkit-react-native#1710] opened 2024-04-19 15:44 UTC
When inputting a bitcoin amount to send an onchain payment, the available savings amount doesn't match the value shown on the home screen due to the required fee. This is not made entirely clear and it can only be assumed, which may be acceptable for an experienced user under normal use.

In this video, I have a low savings balance and when trying to send it shows me I have 0 sats available without any explanation why. This could be improved to reduce confusion/frustration, particularly for new users. E.g. it could say "minus fees" or an icon to hint at the calculation.

https://github.com/synonymdev/bitkit/assets/74595920/c9ae0aee-fe96-40a0-8e60-eebbc600cd9c

**Comment by JeanlChristophe** [comment] 2024-05-23 08:28
I can't reproduce this issue. Closing it

**Closed as completed by JeanlChristophe** 2024-05-23 08:28 UTC

**Comment by catch-21** [comment] 2024-05-23 09:48
It's not a bug to be reproduced, it's a UX suggestion wrt the ambiguous meaning of "AVAILABLE (SAVINGS)".
