### ISSUE TITLE
Unable to see contact after restoring seed

### ISSUE THREAD

**Issue by thisispav** [synonymdev/bitkit-react-native#1636] opened 2024-04-12 08:21 UTC
### Describe the bug

scanned JC's QR code and added him as a contact 
I backed up the seed and wiped the wallet. 
When I re-entered the seed and successfully restored, my contact data was there, but not JC's contact 

testing on Regtest

### Screenshots / Recording

![photo_2024-04-12_11-16-34](https://github.com/synonymdev/bitkit/assets/119061223/795f239f-83d8-41e5-9149-eb6811dbc1e5)
![photo_2024-04-12_11-16-33](https://github.com/synonymdev/bitkit/assets/119061223/578982c2-381e-4281-b2f9-2299296bbb7e)
[bitkit_ldk_logs_1712910048984.zip](https://github.com/synonymdev/bitkit/files/14956098/bitkit_ldk_logs_1712910048984.zip)

### Operating system

Graphene OS Pixel 6A

### Bitkit version

v113

**Comment by catch-21** [comment] 2024-04-12 08:25
I had the same issue when scanning JC's QR to add one profile and then resetting, it did not restore the contact. However, on second attempt with both JC's and Pav's QR to add two profiles it worked as intended.

**Comment by pwltr** [comment] 2024-04-16 09:14
Duplicate of https://github.com/synonymdev/bitkit/issues/1620

**Closed as completed by pwltr** 2024-04-16 09:14 UTC
Labels: bug, triage
